# Generated by Django 3.2.12 on 2022-04-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Dc'), (1, 'Cafe'), (2, 'Other')])),
            ],
        ),
        migrations.CreateModel(
            name='GuildMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gamecode', models.CharField(max_length=10, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Master'), (1, 'Submaster'), (2, 'Writer'), (3, 'Member')])),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='guild.guild')),
            ],
        ),
    ]
