# Generated by Django 3.2.12 on 2022-04-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(0, 'Basic'), (1, 'Light'), (2, 'Dark'), (3, 'Fire'), (4, 'Ground'), (5, 'Water')])),
                ('weak', models.IntegerField(choices=[(0, 'Injured'), (1, 'Downed'), (2, 'Airborne'), (3, 'Injureddowned'), (4, 'Injuredairborne'), (5, 'Downedairborne'), (6, 'All')])),
            ],
        ),
        migrations.CreateModel(
            name='RaidInfo',
            fields=[
                ('round', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('bossA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bossA', to='raid.bossinfo')),
                ('bossB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bossB', to='raid.bossinfo')),
                ('bossC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bossC', to='raid.bossinfo')),
                ('bossD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bossD', to='raid.bossinfo')),
            ],
        ),
        migrations.CreateModel(
            name='GuildSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnificationA', models.FloatField(default=1.0)),
                ('magnificationB', models.FloatField(default=1.0)),
                ('magnificationC', models.FloatField(default=1.0)),
                ('magnificationD', models.FloatField(default=1.0)),
                ('magnificationStartDate', models.DateField()),
                ('magnificationEndDate', models.DateField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild.guild')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.raidinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('boss', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')])),
                ('damage', models.IntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild.guild')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild.guildmember')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.raidinfo')),
            ],
        ),
    ]
