# Generated by Django 3.2.12 on 2022-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossinfo',
            name='weak',
            field=models.IntegerField(choices=[(0, 'Injured'), (1, 'Downed'), (2, 'Airborne'), (3, 'Injureddowned'), (4, 'Injuredairborne'), (5, 'Downedairborne'), (6, 'All')]),
        ),
    ]
